# Generated by Django 5.1.7 on 2025-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalId', models.CharField(max_length=16)),
                ('medicamentName', models.CharField(max_length=30)),
                ('lastSentNotification', models.DateTimeField()),
                ('lastPlannedNotificationLimit', models.DateTimeField(null=True)),
                ('receptionInterval', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
